# Generated by Django 4.0.3 on 2022-04-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('layout_id', models.AutoField(primary_key=True, serialize=False)),
                ('layout_title', models.CharField(blank=True, max_length=50, null=True)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('columns', models.IntegerField(blank=True, null=True)),
                ('layout', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
