# Generated by Django 4.0.3 on 2022-04-19 14:47

from django.db import migrations, models
import processing.models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_seatlayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location_from', models.CharField(blank=True, max_length=100, null=True)),
                ('location_to', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('departure_stop', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_stop', models.CharField(blank=True, max_length=100, null=True)),
                ('lower_deck', models.CharField(blank=True, max_length=20, null=True)),
                ('upper_deck', models.CharField(blank=True, max_length=20, null=True)),
                ('boarding_points', models.TextField(blank=True, null=True)),
                ('dropping_points', models.TextField(blank=True, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('staff', models.TextField(blank=True, null=True)),
                ('cancellation_available', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField(blank=True, null=True)),
                ('photo1', models.FileField(blank=True, null=True, upload_to=processing.models.bus_image)),
                ('photo2', models.FileField(blank=True, null=True, upload_to=processing.models.bus_image)),
                ('photo3', models.FileField(blank=True, null=True, upload_to=processing.models.bus_image)),
                ('photo4', models.FileField(blank=True, null=True, upload_to=processing.models.bus_image)),
                ('photo5', models.FileField(blank=True, null=True, upload_to=processing.models.bus_image)),
                ('photo6', models.FileField(blank=True, null=True, upload_to=processing.models.bus_image)),
            ],
        ),
        migrations.AlterField(
            model_name='seatlayout',
            name='layout_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
