# Generated by Django 4.0.3 on 2022-04-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_bus_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='first_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_timing',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
