# Generated by Django 4.0.3 on 2022-04-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_bus_first_timing_bus_last_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatlayout',
            name='seat_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='first_timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='last_timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
