# Generated by Django 4.0.3 on 2022-04-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_seatlayout_seat_type_alter_bus_first_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seats',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
