# Generated by Django 4.0.3 on 2022-04-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_bus_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='seats',
        ),
        migrations.AddField(
            model_name='bus',
            name='seats1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='seats2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='totalSeats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
