# Generated by Django 4.0.3 on 2022-04-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_remove_bus_seats_bus_seats1_bus_seats2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='paid_status',
            field=models.CharField(default='Not Paid', max_length=100),
        ),
    ]
