# Generated by Django 4.0.3 on 2022-04-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_bus_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='ticketsSold',
            field=models.IntegerField(default=0),
        ),
    ]
