# Generated by Django 4.0.3 on 2022-04-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0012_bus_reservedseatslower_bus_reservedseatsupper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='totalSeats',
            new_name='seatsLeft',
        ),
    ]
