# Generated by Django 4.0.3 on 2022-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0014_ticket_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
