# Generated by Django 4.0.3 on 2022-04-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0015_ticket_ticket_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_no',
            new_name='ticket_url',
        ),
    ]
