# Generated by Django 4.0.3 on 2022-05-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0017_ticket_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancellation_available',
            field=models.BooleanField(default=False),
        ),
    ]
