# Generated by Django 4.0.3 on 2022-05-16 07:39

from django.db import migrations, models
import processing.models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0019_ticket_exhausted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='photo1',
            field=models.FileField(blank=True, null=True, upload_to=processing.models.bus_image),
        ),
        migrations.AddField(
            model_name='bus',
            name='photo2',
            field=models.FileField(blank=True, null=True, upload_to=processing.models.bus_image),
        ),
        migrations.AddField(
            model_name='bus',
            name='photo3',
            field=models.FileField(blank=True, null=True, upload_to=processing.models.bus_image),
        ),
        migrations.AddField(
            model_name='bus',
            name='photo4',
            field=models.FileField(blank=True, null=True, upload_to=processing.models.bus_image),
        ),
        migrations.AddField(
            model_name='bus',
            name='photo5',
            field=models.FileField(blank=True, null=True, upload_to=processing.models.bus_image),
        ),
        migrations.AddField(
            model_name='bus',
            name='photo6',
            field=models.FileField(blank=True, null=True, upload_to=processing.models.bus_image),
        ),
    ]
